New: Added mcq support for _canShowCorrectness
adaptlearning/adapt-contrib-vanilla pull request #527
Opened 2024-09-10 10:49 UTC by oliverfoster

part of https://github.com/adaptlearning/adapt_framework/issues/3597

### New
* Added support for _canShowCorrectness

2024-09-11 12:10 UTC, kirsty-hames requested changes
Looking good thanks. Please see comment regarding selector name change.

2024-09-11 12:10 UTC, kirsty-hames commented on less/plugins/adapt-contrib-mcq/mcq.less
> +  .mcq__text {
`.mcq__text` should be `.mcq-item__text`

2024-09-12 09:08 UTC, joe-allen-89 approved these changes
👍

2024-10-03 16:18 UTC, simondate approved these changes

2024-10-08 09:35 UTC, cahirodoherty-learningpool approved these changes
👀

2024-10-08 09:44 UTC, merged